version: 2.1
jobs:
  day_1_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 1 tests"
          command: "cargo test"
          working_directory: "day_1"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_1"
      - run:
          name: "Day 1 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_1"
      
  day_2_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 2 tests"
          command: "cargo test"
          working_directory: "day_2"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_2"
      - run:
          name: "Day 2 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_2"
  
  day_3_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 3 tests"
          command: "cargo test"
          working_directory: "day_3"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_3"
      # - run:
      #     name: "Day 3 formatting"
      #     command: "cargo clippy -- -Dwarnings"
      #     working_directory: "day_3"

  day_4_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 4 tests"
          command: "cargo test"
          working_directory: "day_4"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_4"
      - run:
          name: "Day 4 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_4"

  day_5_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 5 tests"
          command: "cargo test"
          working_directory: "day_5"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_5"
      - run:
          name: "Day 5 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_5"

  day_6_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 6 tests"
          command: "cargo test"
          working_directory: "day_6"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_6"
      - run:
          name: "Day 6 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_6"

  day_7_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 7 tests"
          command: "cargo test"
          working_directory: "day_7"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_7"
      - run:
          name: "Day 7 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_7"
  day_8_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 8 tests"
          command: "cargo test"
          working_directory: "day_8"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_8"
      - run:
          name: "Day 8 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_8"

workflows:
  tests:
    jobs:
      - day_1_test
      - day_2_test
      - day_3_test
      - day_4_test
      - day_5_test
      - day_6_test
      - day_7_test
      - day_8_test
