version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          base-revision: main
          config-path: .circleci/solution_check.yml
          mapping: |
            day_01/.* day_1_test true
            day_02/.* day_2_test true
            day_03/.* day_3_test true
            day_04/.* day_4_test true
            day_05/.* day_5_test true
            day_06/.* day_6_test true
            day_07/.* day_7_test true
            day_08/.* day_8_test true
            day_09/.* day_9_test true
            day_10/.* day_10_test true
            day_11/.* day_11_test true
            day_12/.* day_12_test true
            day_13/.* day_13_test true
            day_14/.* day_14_test true
            day_15/.* day_15_test true
            day_16/.* day_16_test true
            day_18/.* day_18_test true
            day_19/.* day_19_test true
            day_20/.* day_20_test true
            day_21/.* day_21_test true
            day_22/.* day_22_test true
            day_23/.* day_23_test true
            day_24/.* day_24_test true
