version: 2.1
jobs:
  day_1_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 1 tests"
          command: "cargo test"
          working_directory: "day_1"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_1"
      - run:
          name: "Day 1 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_1"
      
  day_2_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 2 tests"
          command: "cargo test"
          working_directory: "day_2"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_2"
      - run:
          name: "Day 2 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_2"

  day_4_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 4 tests"
          command: "cargo test"
          working_directory: "day_4"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_4"
      - run:
          name: "Day 4 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_4"

workflows:
  tests:
    jobs:
      - day_1_test
      - day_2_test
      - day_4_test
