version: 2.1
jobs:
  day_1_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 1 tests"
          command: "cargo test"
          working_directory: "day_1"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_1"
      - run:
          name: "Day 1 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_1"
      
  day_2_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 2 tests"
          command: "cargo test"
          working_directory: "day_2"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_2"
      - run:
          name: "Day 2 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_2"
  
  day_3_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 3 tests"
          command: "cargo test"
          working_directory: "day_3"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_3"
      # - run:
      #     name: "Day 3 formatting"
      #     command: "cargo clippy -- -Dwarnings"
      #     working_directory: "day_3"

  day_4_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 4 tests"
          command: "cargo test"
          working_directory: "day_4"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_4"
      - run:
          name: "Day 4 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_4"

  day_5_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 5 tests"
          command: "cargo test"
          working_directory: "day_5"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_5"
      - run:
          name: "Day 5 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_5"

  day_6_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 6 tests"
          command: "cargo test"
          working_directory: "day_6"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_6"
      - run:
          name: "Day 6 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_6"

  day_7_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 7 tests"
          command: "cargo test"
          working_directory: "day_7"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_7"
      - run:
          name: "Day 7 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_7"
  day_8_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 8 tests"
          command: "cargo test"
          working_directory: "day_8"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_8"
      - run:
          name: "Day 8 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_8"
  day_9_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 9 tests"
          command: "cargo test"
          working_directory: "day_9"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_9"
      - run:
          name: "Day 9 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_9"
  day_10_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 10 tests"
          command: "cargo test"
          working_directory: "day_10"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_10"
      - run:
          name: "Day 10 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_10"
  day_11_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 11 tests"
          command: "cargo test"
          working_directory: "day_11"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_11"
      - run:
          name: "Day 11 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_11"
  day_12_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 12 tests"
          command: "cargo test"
          working_directory: "day_12"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_12"
      - run:
          name: "Day 12 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_12"
  day_13_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 13 tests"
          command: "cargo test"
          working_directory: "day_13"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_13"
      - run:
          name: "Day 13 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_13"
  day_14_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 14 tests"
          command: "cargo test"
          working_directory: "day_14"
      - run:
          name: "Install clippy"
          command: "rustup component add clippy"
          working_directory: "day_14"
      - run:
          name: "Day 14 formatting"
          command: "cargo clippy -- -Dwarnings"
          working_directory: "day_14"

workflows:
  tests:
    jobs:
      - day_1_test
      - day_2_test
      - day_3_test
      - day_4_test
      - day_5_test
      - day_6_test
      - day_7_test
      - day_8_test
      - day_9_test
      - day_10_test
      - day_11_test
      - day_12_test
      - day_13_test
      - day_14_test
