version: 2.1
jobs:
  day_1_test:
    docker:
      - image: rust:1.74
    steps:
      - checkout
      - run:
          name: "Day 1 tests"
          command: "cargo test"
          working_directory: "day_1"

workflows:
  tests:
    jobs:
      - day_1_test
